[workspace]
resolver = "2"
members = [
  "core", 
  "core/prisma", 
  "core/integration-tests", 
  "apps/desktop/src-tauri", 
  "apps/tui", 
  "apps/server"
]

[workspace.package]
version = "0.0.0"
rust-version = "1.64.0"

[workspace.dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.1", features = [
  'rspc',
  # 'sqlite-create-many',
  # "migrations",
  # "sqlite",
] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.21.2", features = [
  # feature for the internal channels (internal communication)
  "sync", 
  # this is needed for tokio::spawn multi-threaded
  "rt-multi-thread"
] }

### DEV UTILS ###
specta = "0.0.2"

### Error Handling + Logging ###
tracing = "0.1.36"
thiserror = "1.0.37"