[workspace]
resolver = "2"
members = ["core", "core/prisma", "core/integration-tests", "apps/desktop/src-tauri", "apps/tui", "apps/server"]

[workspace.package]
version = "0.0.0"
rust-version = "1.64.0"

[workspace.dependencies]
rocket =  { version = "0.5.0-rc.2", features =  ["json" ] }
serde = { version = "1.0", features = ["derive"] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.1", features = [
  'rspc',
  # 'sqlite-create-many',
  # "migrations",
  # "sqlite",
] }

### DEV UTILS ###
schemars = "0.8.10"
specta = "0.0.2"

## ERROR HANDLING + LOGGING ###
log = "0.4.0"
thiserror = "1.0.30"