[package]
name = "stump_server"
version.workspace = true
edition = "2021"
default-run = "stump_server"

[dependencies]
stump_core = { path = "../../core" }
prisma-client-rust.workspace = true
serde.workspace = true

### Rocket / Generic Server ### 
rocket.workspace = true
rocket_okapi = { version = "0.8.0-rc.2", features = ["rapidoc", "swagger"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master" }
rocket-session-store = { git = "https://github.com/aaronleopold/rocket-session-store", branch = "develop", features = ["okapi"] }

### Dev Utils ###
schemars.workspace = true
specta.workspace = true

### Error Handling + Logging ###
thiserror.workspace = true
log.workspace = true

### Auth ###
bcrypt = "0.10.1"
base64 = "0.13.0"

### Platform Specific Deps ###
[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }

[target.armv7-unknown-linux-musleabihf.dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }