[package]
name = "stump"
version = "0.0.1"
edition = "2021"
default-run = "stump"

[features]
default = ["libarchive"]
libarchive = ["dep:compress-tools"]

[dependencies]
# core dependencies
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.5.2" }
serde = { version = "1.0", features = ["derive"] }
rocket =  { version = "0.5.0-rc.2", features =  ["json" ] }

# auth / security
rocket-session-store = { git = "https://github.com/aaronleopold/rocket-session-store", branch = "develop", features = ["okapi"] }
bcrypt = "0.10.1"
# FIXME: not pointing to master caused some compilation issues. It's in alpha, so :)
# See https://github.com/lawliet89/rocket_cors/pull/108. Should be updated on next release
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master" }

# dev utils
rocket_okapi = { version = "0.8.0-rc.2", features = ["rapidoc", "swagger"] }
schemars = "0.8.10"

# misc utils
include_dir = "0.7.2"
urlencoding = "2.1.0"
cuid = "1.2.0"
async-trait = "0.1.53"
xml-rs = "0.8.4" # used for creating XML docs
serde-xml-rs = "0.5.1" # used for serializing/deserializing xml

# files & hashing
walkdir = "2.3.2"
dirs = "4.0.0"
infer = "0.7.0"
image = "0.24.2"
webp = "0.2.2"
zip = "0.5.13"
epub = "1.2.3"
unrar = { git = "https://github.com/aaronleopold/unrar.rs", branch = "aleopold--read-bytes" }
compress-tools = { version = "0.13.0", optional = true }
base64 = "0.13.0"
data-encoding = "2.3.2"
ring = "0.16.20"

# error handling & logging
anyhow = "1.0.57"
thiserror = "1.0.30"
log = "0.4.0"
fern = "0.6.1"
figment = { version = "0.10.6", features = ["toml", "env"] }
toml = "0.5.9"
futures = "0.3.21"

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }

[target.armv7-unknown-linux-musleabihf.dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }
