[package]
name = "stump_core"
version.workspace = true
edition = "2021"

[dependencies]
rocket.workspace = true
serde.workspace = true
prisma-client-rust.workspace = true

specta.workspace = true
schemars.workspace = true

rayon = "1.5.3"
futures = "0.3.21"
async-trait = "0.1.53"

### MISC UTILS ###
urlencoding = "2.1.0"
cuid = "1.2.0"
xml-rs = "0.8.4" # used for creating XML docs
serde-xml-rs = "0.5.1" # used for serializing/deserializing xml

### FILESYSTEM UTILS ###
walkdir = "2.3.2"
dirs = "4.0.0"
trash = "2.0"
infer = "0.7.0"
image = "0.24.2"
webp = "0.2.2"
zip = "0.5.13"
epub = "1.2.3"
unrar = { git = "https://github.com/aaronleopold/unrar.rs", branch = "aleopold--read-bytes" }
data-encoding = "2.3.2"
include_dir = "0.7.2"
ring = "0.16.20"

## ERROR HANDLING + LOGGING ###
thiserror.workspace = true
log.workspace = true
fern = "0.6.1"
# figment = { version = "0.10.6", features = ["toml", "env"] }
toml = "0.5.9"